/**
 * @file tuya_config.h
 * @brief IoT specific configuration file
 */

#ifndef TUYA_CONFIG_H_
#define TUYA_CONFIG_H_

#include "tuya_cloud_types.h"

/**
 * @brief configure the product information
 *
 * TUYA_PRODUCT_ID: PID, comes from the Kconfig symbol (app_default.config)
 * TUYA_OPENSDK_UUID: UUID, the unique ID of the device (license)
 * TUYA_OPENSDK_AUTHKEY: AUTHKEY, the private key of the device (license)
 *
 * When the module carries a pre-burned Tuya license, tuya_authorize_read()
 * loads UUID/AuthKey from the license storage and these defines are not used.
 *
 * warning: please replace these production information with your product id and license,
 * otherwise the demo cannot work.
 */

#ifndef TUYA_PRODUCT_ID
#define TUYA_PRODUCT_ID "u9bu0onwwwj6eyov"
#endif

#define TUYA_OPENSDK_UUID    "uuidxxxxxxxxxxxxxxxx"             // Please change the correct uuid
#define TUYA_OPENSDK_AUTHKEY "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" // Please change the correct authkey

/**
 * @brief PINCODE for AP provisioning
 *
 * TUYA_NETCFG_PINCODE: a random PINCODE for AP provisioning, PINCODE was generated BY TUYA PMS system!!!
 *
 * WARNING: PINCODE is mandatory for AP provisioning
 */
// #define TUYA_NETCFG_PINCODE   "69832860"

#endif