// DP-HASH: 9c258a5508359627
// Auto-generated by `tuyaopen dp generate --target embedded` — do not edit.
// Source: .tuyaopen/platform/product-<pid>.json (selected DPs only).
// Regenerate after DPs change in the TuyaOpen IDE or via the CLI.
#ifndef TUYA_DP_PROFILE_H
#define TUYA_DP_PROFILE_H

/* DP IDs */
#define DPID_STATUS              2
#define DPID_VOLUME_SET          6
#define DPID_CONVERSATIONAL_MODE 9
#define DPID_MUTE                101
#define DPID_LED_SWITCH          102
#define DPID_STUDY_MODE          103
#define DPID_FOCUS_TIMER         104

/* Value-DP bounds (from cloud property block) */
#define DPID_VOLUME_SET_MIN 0
#define DPID_VOLUME_SET_MAX 100
#define DPID_VOLUME_SET_SCALE 0
#define DPID_VOLUME_SET_STEP 1
#define DPID_FOCUS_TIMER_MIN 0
#define DPID_FOCUS_TIMER_MAX 180
#define DPID_FOCUS_TIMER_SCALE 0
#define DPID_FOCUS_TIMER_STEP 5

/* Enum-DP ranges (informational — mirror these in your C enum) */
/* DPID_STATUS (enum): "standby", "charging", "charge_done", "playing", "goto_charge", "sleep", "following", "moving", "on", "off" */
/* DPID_CONVERSATIONAL_MODE (enum): "hold", "key", "weakup", "free" */
/* DPID_STUDY_MODE (enum): "general", "physics", "chemistry", "biology", "solve_jee_pyq", "solve_neet_pyq", "ncert", "book_reading", "module_question", "test_mode", "exam_mode" */

#endif /* TUYA_DP_PROFILE_H */
