import { keyBy } from 'lodash-es';
import { GetSmartDeviceModelDpSchema } from '@ray-js/panel-sdk';

// Auto-generated by TuyaOpen IDE — do not edit manually.
// Regenerate via the MiniApp panel's "Sync DPs from Cloud" action.
export const deviceSchema = [] as const;

export const deviceSchemaMap = keyBy(deviceSchema, 'code') as GetSmartDeviceModelDpSchema<typeof deviceSchema>;
